### ISSUE TITLE
cppcheck: error: unrecognized command line option: "-c".

### ISSUE THREAD

**Issue by andkae** [neszt/cppcheck-docker#5]
Hi Neszt,

thanks for providing the docker Conatiner. When i use your docker image inside gitlab i encounter the error

```bash
cppcheck: error: unrecognized command line option: "-c".
```

My yml file looks like follows:
```yml
check:
  image: neszt/cppcheck-docker:latest
  except:
    changes:
      - 'doc/**'
      - 'README.md'
  script:
    - bash -c "echo $PWD" 
```

Do you have an idea what could cause the issue?

Thanks for your help.

**Comment by andkae** [comment]
One addition if i use inside gitlab-ci.yml

```yml
  image: 
    name:       neszt/cppcheck-docker:latest
    entrypoint: ["/bin/sh"]
```

i encounter the error

```bash
/bin/sh: can't open 'sh': No such file or directory
```

Is there no shell in this docker?

**Comment by neszt** [comment]
> ```shell
> cppcheck: error: unrecognized command line option: "-c".
> ```

There is an ENTRYPOINT in the dockerfile, so this cannot be overridden, the cppcheck command is executed anyway. That's why you get an "unrecognized command" error, because this is also returned by cppcheck, it has no such argument.

This is a dockerized cppcheck, just mount the files to be checked in the /src directory and run the check as described in the README.

**Comment by andkae** [comment]
Okay. Thanks for the comment. I run this docker in a Gitlab Environment. That means I have no access to the docker run command. Do you have a suggestion to deal with it?

Thanks BR,
Andreas

**Comment by neszt** [comment]
> Okay. Thanks for the comment. I run this docker in a Gitlab Environment. That means I have no access to the docker run command. Do you have a suggestion to deal with it?

What exactly is the purpose of using cppcheck docker in gitlab? Could you give me a full picture so I can understand better?

**Comment by andkae** [comment]
> What exactly is the purpose of using cppcheck docker in gitlab? Could you give me a full picture so I can understand better?

For sure. I use the cppcheck-docker inside gitlab as CI/CD job. That means i set up the .gitlab-ci.yml. My content looks like follows:

```yml
check:
  image: 
    name:       neszt/cppcheck-docker:latest
  except:
    changes:
      - 'doc/**'
      - 'README.md'
  script:
    - echo $PWD
```

This script describes the gitlab CI/CD job. At the moment i know no way to setup an mount point. In the section _script_ is then the command to be excuted noted down. in my snippet its only ```echo $PWD```.  In my opinon transform gitlab the command  cppcheck -c "cmd" derived from ```bash -c "cmd"```. But this is only a guess.

**Comment by neszt** [comment]
It may indeed be as you suppose.

I read more and see that this is a known issue with gitlab, I hope you can find a solution here: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692

**Comment by andkae** [comment]
Great catch! Now its working:

```yml
check:
  image: 
    name:       neszt/cppcheck-docker:latest
    entrypoint: [""]    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692
  except:
    changes:
      - 'doc/**'
      - 'README.md'
  script:
    - /bin/sh
    - cppcheck --help
```
